# Generated by Django 5.2.4 on 2025-07-05 10:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('source_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('note', 'Note'), ('other', 'Other')], default='other', max_length=20)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'context_entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_type', 'context_date'], name='context_ent_source__152b14_idx'), models.Index(fields=['is_processed'], name='context_ent_is_proc_99a4e5_idx')],
            },
        ),
    ]
