# Generated by Django 5.2.4 on 2025-07-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='context',
            new_name='context_source__775d1e_idx',
            old_name='context_ent_source__152b14_idx',
        ),
        migrations.RenameIndex(
            model_name='context',
            new_name='context_is_proc_9e0ccc_idx',
            old_name='context_ent_is_proc_99a4e5_idx',
        ),
        migrations.AlterModelTable(
            name='context',
            table='context',
        ),
    ]
