# Generated by Django 5.2.4 on 2025-07-07 11:47

from django.db import migrations
import uuid

def create_initial_categories(apps, schema_editor):
    Category = apps.get_model('tasks', 'Category')
    Category.objects.bulk_create([
        Category(
            id=uuid.uuid4(),
            name='Home',
            color='#3B82F6',
            usage_frequency=0
        ),
        Category(
            id=uuid.uuid4(),
            name='Work',
            color='#10B981',
            usage_frequency=0
        ),
        Category(
            id=uuid.uuid4(),
            name='Personal',
            color='#F59E0B',
            usage_frequency=0
        ),
        Category(
            id=uuid.uuid4(),
            name='Health',
            color='#EF4444',
            usage_frequency=0
        ),
        Category(
            id=uuid.uuid4(),
            name='Finance',
            color='#8B5CF6',
            usage_frequency=0
        ),
    ])

class Migration(migrations.Migration):
    
    
    dependencies = [
        ('tasks', '0001_initial'),
    ]
    
    operations = [
        migrations.RunPython(create_initial_categories),
    ]
